apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: sriov-config-dpdk-enp5s0f1
  namespace: openshift-sriov-network-operator
spec:
  deviceType: vfio-pci
  isRdma: false
  mtu: 9000
  needVhostNet: true
  nicSelector:
    pfNames:
    - enp5s0f1#30-49
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  numVfs: 50
  priority: 50
  resourceName: sriov_vfio_1
