# oc new-project sriov-test
# oc create sa priviledged-sa
# oc adm policy add-scc-to-user privileged -z priviledged-sa
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: po-7-vlan100
  namespace: sriov-test
  labels:
    k8s-app: po-7-vlan100
spec:
  replicas: 1
  selector:
        matchLabels:
          app: po-7-vlan100
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: vlan100@vlan100
      name: po-7-vlan100
      labels:
            app: po-7-vlan100
    spec:
      securityContext:
          type: privileged
      serviceAccount: priviledged-sa
      containers:
      - name: po-7-vlan100
        image: quay.io/dmoessne/94-ncat-tools:0.2
        command: ["/bin/sh", "-c"]
        args:
          - |
            ip link add link vlan100 name mcplane type vlan 100
            ip link set mcplane mtu 1500
            ip link set mcplane up
            ip addr add 192.168.100.17/24 dev mcplane
            /start_nc.sh
        resources:
          limits:
            openshift.io/sriov_netdevice_1: 1
          requests:
            openshift.io/sriov_netdevice_1: 1
        securityContext:
           runAsUser: 0
           privileged: true
